apiVersion: v1
kind: Service
metadata:
  name: app-wcpdr
  labels:
    app.kubernetes.io/name: app-wcpdr
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: app-wcpdr
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
