apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mapproxy-conf
  labels:
    app.kubernetes.io/name: mapproxy
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.mapproxy.persistenceSize.mapproxyConf }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  mapproxy-datasource
  labels:
    app.kubernetes.io/name: mapproxy
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.mapproxy.persistenceSize.mapproxyDataSource }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mapproxy-cache
  labels:
    app.kubernetes.io/name: mapproxy
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.mapproxy.persistenceSize.mapproxyCache }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mapproxy-seed
  labels:
    app.kubernetes.io/name: mapproxy
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.mapproxy.persistenceSize.mapproxySeed }}"