apiVersion: v1
kind: Service
metadata:
  name: mapproxy
  labels:
    app.kubernetes.io/name: mapproxy
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: mapproxy
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: mapproxy
      port: 8051
      targetPort: 8051

