apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-data
  labels:
    app.kubernetes.io/name: pg
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storage }}
