apiVersion: v1
kind: Service
metadata:
  name: pg
  labels:
    app.kubernetes.io/name: pg
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: pg
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
