apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.pgSecretName }}
  labels:
    app.kubernetes.io/name: pg
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  {{/* Retrieve exiting secret */}}
  {{- $pgSecretData := (get (lookup "v1" "Secret" .Release.Namespace "{{ .Values.postgresql.pgSecretName }}" | default dict) "data" | default dict) }}
  {{/* If secret doesn't exist, generateing a 32 chars long random string */}}
  {{- $pgPasswd := (get $pgSecretData "postgresql-password" | default (randAlphaNum 32 | b64enc)) }}
  postgresql-password: {{ $pgPasswd | quote }}
